version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
